"use client";

/**
 * mockWebSocket.ts
 *
 * Simulates the FastAPI WebSocket stream so the UI can be developed and
 * demoed without a running backend.
 *
 * ─── TO SWITCH TO YOUR REAL BACKEND ──────────────────────────────────────────
 *
 *   Replace the `MockAgentWebSocket` class with this real implementation:
 *
 *   export class AgentWebSocket {
 *     private ws: WebSocket;
 *
 *     constructor(
 *       query: string,
 *       onMessage: (msg: WsMessage) => void,
 *       onClose: () => void
 *     ) {
 *       this.ws = new WebSocket(`ws://localhost:8000/ws/research?query=${encodeURIComponent(query)}`);
 *       this.ws.onmessage = (e) => onMessage(JSON.parse(e.data));
 *       this.ws.onclose = onClose;
 *       this.ws.onerror = (e) => console.error("WS error", e);
 *     }
 *
 *     disconnect() { this.ws.close(); }
 *   }
 *
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { WsMessage, LogStep } from "@/types";
import { generateId } from "@/lib/utils";

type MessageHandler = (msg: WsMessage) => void;
type CloseHandler = () => void;

interface MockLogScript {
  step: LogStep;
  message: string;
  delayMs: number;
}

function buildScript(query: string): MockLogScript[] {
  return [
    { step: "search",     message: `[🔍] Searching Tavily for "${query}"...`,             delayMs: 600  },
    { step: "fetch",      message: "[🌐] Fetching top 5 source documents...",              delayMs: 900  },
    { step: "analyze",    message: "[🧠] Extracting key facts and entities...",            delayMs: 1200 },
    { step: "reason",     message: "[💡] Running chain-of-thought reasoning pass 1/3...", delayMs: 800  },
    { step: "reason",     message: "[💡] Running chain-of-thought reasoning pass 2/3...", delayMs: 900  },
    { step: "reason",     message: "[💡] Running chain-of-thought reasoning pass 3/3...", delayMs: 700  },
    { step: "synthesize", message: "[📝] Synthesizing findings into structured report...", delayMs: 1400 },
    { step: "save",       message: "[💾] Saving report to artifacts store...",             delayMs: 600  },
    { step: "complete",   message: "[✅] Research complete. Report ready.",                delayMs: 400  },
  ];
}

const MOCK_REPORT_MARKDOWN = (query: string) => `
# Research Report: ${query}

*Generated by AutoAnalyst-Engine · ${new Date().toLocaleDateString("en-US", { dateStyle: "long" })}*

---

## Executive Summary

This autonomous research analysis examines **${query}** across multiple high-signal sources. The findings below represent a synthesis of current literature, real-time data, and structured reasoning chains executed by the agent.

---

## Key Findings

### 1. Market Landscape
Recent developments indicate significant momentum across adjacent domains. Primary actors have increased investment by an estimated **34%** YoY, with emerging frameworks enabling unprecedented throughput at inference time.

### 2. Technical Architecture
The dominant paradigm has shifted toward **Retrieval-Augmented Generation (RAG)** pipelines, where real-time source grounding eliminates hallucination risk. Sub-second latency is now achievable via specialized LPU hardware (Groq).

### 3. Competitive Dynamics
Three primary categories of solutions have emerged:
- **Autonomous agents** — capable of multi-step tool use and self-correction
- **Hybrid retrieval systems** — combining dense and sparse vector search
- **Structured output engines** — enforcing schema-valid JSON from LLM outputs

---

## Methodology

1. Query decomposition via LLM planning step
2. Parallel web search via Tavily API (top-K=5 results)
3. Document chunking and embedding via \`text-embedding-3-large\`
4. Chain-of-thought reasoning across retrieved context
5. Final synthesis with citation grounding

---

## Sources

- [1] Industry Analysis Report — Gartner, 2025
- [2] arXiv:2501.00001 — "Advances in Agentic AI Systems"
- [3] OpenAI Research Blog — "Structured outputs in production"
- [4] Groq Documentation — "LPU Inference Engine"
- [5] Tavily API Docs — "Real-time web search for AI agents"

---

*Report ID: \`${generateId()}\` · Word count: ~380 · Confidence: High*
`.trim();

export class MockAgentWebSocket {
  private timers: ReturnType<typeof setTimeout>[] = [];
  private cancelled = false;

  constructor(
    query: string,
    private onMessage: MessageHandler,
    private onClose: CloseHandler
  ) {
    this.run(query);
  }

  private run(query: string) {
    const script = buildScript(query);
    let elapsed = 0;

    for (const entry of script) {
      elapsed += entry.delayMs;
      const t = setTimeout(() => {
        if (this.cancelled) return;
        this.onMessage({
          type: "log",
          payload: {
            id: generateId(),
            step: entry.step,
            message: entry.message,
            timestamp: new Date().toISOString(),
          },
        });
      }, elapsed);
      this.timers.push(t);
    }

    // Send the report after all logs
    const reportDelay = elapsed + 300;
    const reportTimer = setTimeout(() => {
      if (this.cancelled) return;
      this.onMessage({
        type: "report",
        payload: {
          id: generateId(),
          title: query,
          markdown: MOCK_REPORT_MARKDOWN(query),
          createdAt: new Date().toISOString(),
          wordCount: 380,
          sources: ["Gartner", "arXiv", "OpenAI", "Groq", "Tavily"],
        },
      });

      // Complete signal
      setTimeout(() => {
        if (!this.cancelled) {
          this.onMessage({ type: "complete", payload: { message: "done" } });
          this.onClose();
        }
      }, 300);
    }, reportDelay);
    this.timers.push(reportTimer);
  }

  disconnect() {
    this.cancelled = true;
    this.timers.forEach(clearTimeout);
    this.onClose();
  }
}